In [1]:
import numpy as np
import torch
from torch import nn
from torch_geometric.data import Data
import torch.nn.functional as F
from torch_geometric.nn import GCNConv
from captum.attr import IntegratedGradients
from torch.utils.data import TensorDataset, DataLoader
from pathlib import Path
import yaml
import os
import pandas as pd
import json
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score,
    precision_recall_curve,
    average_precision_score,
    classification_report
)
from tqdm.auto import tqdm

cfg = yaml.safe_load(Path("../../config/model.yaml").read_text())
device = torch.device(
    "cuda" if torch.cuda.is_available() 
    else ("mps" if torch.backends.mps.is_available() else "cpu"))
print(device)

def set_seed(seed):
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
        
set_seed(cfg["seed"])

/Users/ryan/Documents/NUS/Y4S1/DSA4266/network-traffic-classification/.venv/lib/python3.11/site-packages/torch/jit/_script.py:1491: FutureWarning: `torch.jit.script` is deprecated. Please switch to `torch.compile` or `torch.export`.
  warnings.warn(

mps

# Data loading

In [2]:
DATA_DIR = "../../data/processed"
AUG = "augmented_"

# feats
X_train = np.load(f"{DATA_DIR}/{AUG}X_train.npy")
X_val   = np.load(f"{DATA_DIR}/{AUG}X_val.npy")
X_test  = np.load(f"{DATA_DIR}/{AUG}X_test.npy")

# src-des
pairs_train = np.load(f"{DATA_DIR}/{AUG}pairs_train.npy", allow_pickle=True)
pairs_val   = np.load(f"{DATA_DIR}/{AUG}pairs_val.npy", allow_pickle=True)
pairs_test  = np.load(f"{DATA_DIR}/{AUG}pairs_test.npy", allow_pickle=True)

# labels
y_train = np.load(f"{DATA_DIR}/{AUG}y_train.npy")
y_val   = np.load(f"{DATA_DIR}/{AUG}y_val.npy")
y_test  = np.load(f"{DATA_DIR}/{AUG}y_test.npy")

# convert 1 hot encoded np labels to pytorch labels
y_train_t = torch.tensor(np.argmax(y_train, axis=1), dtype=torch.long)
y_val_t   = torch.tensor(np.argmax(y_val, axis=1), dtype=torch.long)
y_test_t  = torch.tensor(np.argmax(y_test, axis=1), dtype=torch.long)

# verify if shapes of train, test and pair the same

# IP-node mapping

In [3]:
# mapping each ip addrress to nodes
unique_ips = np.unique(np.concatenate([pairs_train[:, 0],pairs_train[:, 1]]))

node_to_id = {
    ip: i
    for i, ip in enumerate(unique_ips)
}

print("Num of nodes:", len(node_to_id))

Num of nodes: 63

In [4]:
# train node ids
src_ids_train = np.array([node_to_id[src] for src in pairs_train[:, 0]])
dst_ids_train = np.array([node_to_id[dst] for dst in pairs_train[:, 1]])
src_ids_train_t = torch.tensor(src_ids_train, dtype=torch.long)
dst_ids_train_t = torch.tensor(dst_ids_train, dtype=torch.long)

# val node ids
src_ids_val = np.array([node_to_id[src] for src in pairs_val[:, 0]])
dst_ids_val = np.array([node_to_id[dst] for dst in pairs_val[:, 1]])
src_ids_val_t = torch.tensor(src_ids_val, dtype=torch.long)
dst_ids_val_t = torch.tensor(dst_ids_val, dtype=torch.long)

# test node ids
src_ids_test = np.array([node_to_id[src] for src in pairs_test[:, 0]])
dst_ids_test = np.array([node_to_id[dst] for dst in pairs_test[:, 1]])
src_ids_test_t = torch.tensor(src_ids_test, dtype=torch.long)
dst_ids_test_t = torch.tensor(dst_ids_test, dtype=torch.long)

# Graph structure

In [5]:
## representation for GCN msg passing
# unique structural connection 
graph_connections = np.unique(np.vstack([src_ids_train, dst_ids_train]), axis=1)
# symmetrise for gcn msg passing
reverse_connections = graph_connections[[1, 0], :]

edge_index = np.unique(
    np.concatenate([graph_connections,reverse_connections],axis=1),
    axis = 1)

edge_index = torch.tensor(edge_index,dtype=torch.long)

## Nodes features

In [6]:
# flatten preprocessed seq feature to aggregate
X_edge_train = X_train.reshape(X_train.shape[0],-1)
X_edge_val = X_val.reshape(X_val.shape[0],-1)
X_edge_test = X_test.reshape(X_test.shape[0],-1)

# build node feat from training set only
num_nodes = len(node_to_id)
num_features = X_edge_train.shape[1]

# 1 feat vector per node
node_features = np.zeros((num_nodes, num_features), dtype=np.float32)
node_counts = np.zeros(num_nodes,dtype=np.float32)

for i in range(len(X_edge_train)):

    src = src_ids_train[i]
    dst = dst_ids_train[i]

    # src and des features
    node_features[src] += X_edge_train[i]
    node_features[dst] += X_edge_train[i]

    node_counts[src] += 1
    node_counts[dst] += 1

# mean feat of all training traffic per ip node
for node in range(num_nodes):
    if node_counts[node] > 0:
        node_features[node] /= node_counts[node]

## Nodes + edges features

In [7]:
# edges feats
edge_features_train = torch.tensor(X_edge_train, dtype=torch.float32)
edge_features_val   = torch.tensor(X_edge_val, dtype=torch.float32)
edge_features_test  = torch.tensor(X_edge_test, dtype=torch.float32)

# GCN to generate node embeddings from node and neighbours
x = torch.tensor(node_features,dtype=torch.float32) # nodes feature
data = Data(x=x, edge_index=edge_index).to(device)

## Model def

In [8]:
class GCN(nn.Module):
    def __init__(self, node_input_dim, hidden_dim, embed_dim, edge_feat_dim, classifier_hidden_dim, dropout, num_classes):

        super().__init__()

        self.conv1 = GCNConv(node_input_dim, hidden_dim)
        self.conv2 = GCNConv(hidden_dim, embed_dim)

        self.classifier = nn.Sequential(
            nn.Linear(2 * embed_dim + edge_feat_dim, classifier_hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(classifier_hidden_dim, num_classes)
        )

    def forward(self, x, edge_index, src_ids, dst_ids, edge_features):
        h = F.relu(self.conv1(x, edge_index))
        h = self.conv2(h, edge_index)

        # src node embed + dst node embed + edge feat
        edge_attr = torch.cat([h[src_ids], h[dst_ids], edge_features], dim=1)

        return self.classifier(edge_attr)


gcn_cfg = cfg["GCN"]

model = GCN(
    node_input_dim=num_features,
    hidden_dim=gcn_cfg["hidden_dim"],
    embed_dim=gcn_cfg["embed_dim"],
    edge_feat_dim=X_edge_train.shape[1],
    classifier_hidden_dim=gcn_cfg["classifier_hidden_dim"],
    dropout=gcn_cfg["dropout"],
    num_classes=5,
).to(device)

In [9]:
BATCH_SIZE = gcn_cfg["batch_size"]

train_loader = DataLoader(
    TensorDataset(src_ids_train_t, dst_ids_train_t, edge_features_train, y_train_t),
    batch_size=BATCH_SIZE,
    shuffle=True
)

val_loader = DataLoader(
    TensorDataset(src_ids_val_t, dst_ids_val_t, edge_features_val, y_val_t),
    batch_size=BATCH_SIZE,
    shuffle=False
)

test_loader = DataLoader(
    TensorDataset(src_ids_test_t, dst_ids_test_t, edge_features_test, y_test_t),
    batch_size=BATCH_SIZE,
    shuffle=False
)

In [10]:
model = model.to(device)

# to handle class
class_weights = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(y_train_t.numpy()),
    y=y_train_t.numpy()
)
class_weights = torch.tensor(class_weights, dtype=torch.float32, device=device)

# loss fn and optimiser
loss_fn = nn.CrossEntropyLoss(weight=class_weights)
optimizer = torch.optim.Adam(
    model.parameters(),
    lr=gcn_cfg["lr"],
    weight_decay=gcn_cfg["weight_decay"]
)

In [11]:
def train_gcn(model, data, dataloader, loss_fn, optimizer, device):
    model.train()
    train_loss = 0

    x = data.x
    edge_index = data.edge_index

    for src, dst, edge_feat, y in dataloader:
        src, dst = src.to(device), dst.to(device)
        edge_feat, y = edge_feat.to(device), y.to(device)

        optimizer.zero_grad()

        logits = model(x, edge_index, src, dst, edge_feat)
        loss = loss_fn(logits, y)

        loss.backward()
        optimizer.step()

        train_loss += loss.item()

    return train_loss / len(dataloader)

def compute_metrics(probs, preds, labels, num_classes=5):
    # multiclass need to use 1 hot
    labels_onehot = np.eye(num_classes)[labels]

    return {
        "f1": f1_score(labels, preds, average="macro", zero_division=0),
        "precision": precision_score(labels, preds, average="macro", zero_division=0),
        "recall": recall_score(labels, preds, average="macro", zero_division=0),
        "pr_auc": average_precision_score(labels_onehot, probs, average="macro"),
        "report": classification_report(
            labels,
            preds,
            target_names=["Backdoor", "CommInj", "DoS", "Reconn", "normal"],
            digits=4,
            zero_division=0
        )
    }

def evaluate_gcn(model, data, dataloader, loss_fn, device, num_classes=5):
    model.eval()
    val_loss = 0
    all_probs, all_preds, all_labels = [], [], []

    x = data.x.to(device)
    edge_index = data.edge_index.to(device)

    with torch.no_grad():
        for src, dst, edge_feat, y in dataloader:
            src, dst = src.to(device), dst.to(device)
            edge_feat, y = edge_feat.to(device), y.to(device)

            logits = model(x, edge_index, src, dst, edge_feat)
            val_loss += loss_fn(logits, y).item()

            # prob and pred for each batch
            all_probs.append(torch.softmax(logits, dim=1).cpu().numpy())
            all_preds.append(logits.argmax(dim=1).cpu().numpy())
            all_labels.append(y.cpu().numpy())

    # flatten into 1 array
    probs = np.concatenate(all_probs)
    preds = np.concatenate(all_preds)
    labels = np.concatenate(all_labels)

    metrics = compute_metrics(probs, preds, labels, num_classes)
    metrics["loss"] = val_loss / len(dataloader)

    return metrics

In [12]:
EPOCHS = gcn_cfg["epochs"]
PATIENCE = gcn_cfg["patience"]

best_pr_auc = 0.0
patience_left = PATIENCE
ckpt_path = f"../../models/gcn_{AUG}best.pt"
os.makedirs(os.path.dirname(ckpt_path), exist_ok=True)

pbar = tqdm(range(EPOCHS), desc="Training GCN")

for epoch in pbar:
    train_loss = train_gcn(model, data, train_loader, loss_fn, optimizer, device)
    val_metrics = evaluate_gcn(model, data, val_loader, loss_fn, device)

    pbar.set_postfix(
        train=f"{train_loss:.4f}",
        val=f"{val_metrics['loss']:.4f}",
        f1=f"{val_metrics['f1']:.4f}",
        pr_auc=f"{val_metrics['pr_auc']:.4f}"
    )

    if val_metrics["pr_auc"] > best_pr_auc:
        best_pr_auc = val_metrics["pr_auc"]
        torch.save(model.state_dict(), ckpt_path)
        patience_left = PATIENCE
    else:
        patience_left -= 1

    if patience_left <= 0:
        tqdm.write(f"Early stopping at epoch {epoch + 1}")
        break

Training GCN:   0%|          | 0/50 [00:00<?, ?it/s]

Early stopping at epoch 34

In [ ]:
# Baseline model performance
baseline_gcn_ckpt = f"../../models/gcn_best.pt"
model.load_state_dict(torch.load(baseline_gcn_ckpt, map_location=device))

test_metrics = evaluate_gcn(model,data,test_loader,loss_fn,device)
print(
    f"Test Loss: {test_metrics['loss']:.4f} | "
    f"F1: {test_metrics['f1']:.4f} | "
    f"Precision: {test_metrics['precision']:.4f} | "
    f"Recall: {test_metrics['recall']:.4f} | "
    f"PR-AUC: {test_metrics['pr_auc']:.4f}"
)

print("\nClassification Report:")
print(test_metrics["report"])

Test Loss: 0.0957 | F1: 0.9792 | Precision: 0.9796 | Recall: 0.9792 | PR-AUC: 0.9892

Classification Report:
              precision    recall  f1-score   support

    Backdoor     0.9512    1.0000    0.9750        39
     CommInj     0.9800    0.9608    0.9703        51
         DoS     1.0000    1.0000    1.0000        91
      Reconn     0.9667    0.9355    0.9508        31
      normal     1.0000    1.0000    1.0000     47152

    accuracy                         0.9999     47364
   macro avg     0.9796    0.9792    0.9792     47364
weighted avg     0.9999    0.9999    0.9999     47364

In [13]:
# Augmented model performance
model.load_state_dict(torch.load(ckpt_path, map_location=device))
test_metrics = evaluate_gcn(model,data,test_loader,loss_fn,device)
print(
    f"Test Loss: {test_metrics['loss']:.4f} | "
    f"F1: {test_metrics['f1']:.4f} | "
    f"Precision: {test_metrics['precision']:.4f} | "
    f"Recall: {test_metrics['recall']:.4f} | "
    f"PR-AUC: {test_metrics['pr_auc']:.4f}"
)

print("\nClassification Report:")
print(test_metrics["report"])

Test Loss: 0.0741 | F1: 0.9755 | Precision: 0.9771 | Recall: 0.9741 | PR-AUC: 0.9910

Classification Report:
              precision    recall  f1-score   support

    Backdoor     0.9500    0.9744    0.9620        39
     CommInj     1.0000    0.9608    0.9800        51
         DoS     1.0000    1.0000    1.0000        91
      Reconn     0.9355    0.9355    0.9355        31
      normal     1.0000    1.0000    1.0000     47152

    accuracy                         0.9999     47364
   macro avg     0.9771    0.9741    0.9755     47364
weighted avg     0.9999    0.9999    0.9999     47364

# Explainability

In [14]:
# each flow has its own copy of the 63node graph
# such that each interpolation is indepedent on the other
class GraphIG(nn.Module):
    """
    to compute batch gradient during IG since require multiple interpolated version of orignal input
    create a large graph of disconnected copies of orignal graph
    each graph has its own node-feature but same connection
    for producing 1 prediction for 1 flow
    """
    def __init__(self, model, edge_index, num_nodes):
        super().__init__()
        self.model = model
        self.edge_index = edge_index
        self.num_nodes = num_nodes

    def forward(self, x_b, ef, src, dst):
        B, N = x_b.shape[0], self.num_nodes
        offs = torch.arange(B, device=x_b.device) * N
        # B disjoint copies of the IP graph
        ei = (self.edge_index.unsqueeze(1) + offs.view(1, -1, 1)).reshape(2, -1)
        return self.model(x_b.reshape(B * N, -1), ei, src + offs, dst + offs, ef)


model.load_state_dict(torch.load(ckpt_path, map_location=device))
model.eval()

graphig = GraphIG(model, data.edge_index, data.num_nodes).to(device)
ig = IntegratedGradients(graphig)

In [15]:
def ig_attributions(idx, n_steps=100, chunk=64):
    """
    calc ig for selected test flows

    For each flow:
        - get attack class predicted by gcn
        - run n step of interpolation for graph node and flow feature from zero baseline to original values
        - at each interpolation point, run  GCN and calc gradients of pred class logit with respect to both feature inputs
        - combine gradient from the n step and multiply with orignal input - baseline
    """
    attr_graph, attr_direct, true_labels, pred_labels = [], [], [], []
    for i in range(0, len(idx), chunk):
        j = idx[i:i + chunk]
        src = src_ids_test_t[j].to(device)
        dst = dst_ids_test_t[j].to(device)
        ef = edge_features_test[j].to(device)
        y = y_test_t[j].to(device)
        x_b = data.x.unsqueeze(0).expand(len(j), -1, -1).contiguous()

        with torch.no_grad():
            pred = graphig(x_b, ef, src, dst).argmax(dim=1)

        # a_x: each row is ig attrib of 1 feat of one IP node to attack-class logit
        # a_ef: each row is the ig attrib of 1 direct feat of the target network flow
        a_x, a_ef = ig.attribute(
            inputs=(x_b, ef),
            # interpolate from baseline 0 for graph and flow to orignal
            baselines=(torch.zeros_like(x_b), torch.zeros_like(ef)),
            target=pred, # explain the pred class logit
            additional_forward_args=(src, dst),
            n_steps=n_steps,
            internal_batch_size=256
        )
        attr_graph.append(a_x.detach().cpu())
        attr_direct.append(a_ef.cpu())
        true_labels.append(y.cpu())
        pred_labels.append(pred.cpu())

    return torch.cat(attr_graph), torch.cat(attr_direct), torch.cat(true_labels), torch.cat(pred_labels)

# random sample from each class
# keeping max sample per class at 200
def balanced_idx(y, per_class=200, seed=42):
    rng = np.random.default_rng(seed)
    idx = [rng.choice(np.where(y == c)[0], min(per_class, (y == c).sum()), replace=False)
           for c in np.unique(y)]
    return torch.tensor(np.concatenate(idx))

idx = balanced_idx(y_test_t.numpy(), per_class=200)
A_graph, A_direct, y_true, y_pred = ig_attributions(idx)

In [16]:
def calculate_importance(A_graph, A_direct):
    """
    A_graph:  [num_flows, 63, 295]
    A_direct: [num_flows, 295]
    """
    num_flows = A_graph.shape[0]

    # reshape to get timestep back from flatten feats
    graph = A_graph.reshape(num_flows, 63, 5, 59)
    direct = A_direct.reshape(num_flows, 5, 59)

    # abs attribution across all node and the 5 timestep
    graph_imp = graph.abs().sum(dim=(1, 2))  # [num_flows, 59]
    direct_imp = direct.abs().sum(dim=1)  # [num_flows, 59]
    combined_imp = graph_imp + direct_imp

    return graph_imp, direct_imp, combined_imp

graph_importance, flow_importance, total_importance = calculate_importance(A_graph,A_direct)

with open("../../data/processed/feature_cols.json") as f:
    feature_info = json.load(f)

feature_names = (feature_info["numeric"]+ feature_info["categorical"])

# global feature importance
global_importance = pd.DataFrame({
    "feature": feature_names,
    "graph_path":  graph_importance.mean(0).numpy(),
    "direct_path": flow_importance.mean(0).numpy(),
    "total":       total_importance.mean(0).numpy(),
}).sort_values("total", ascending=False)

global_importance.head(20)

             feature  graph_path  direct_path     total
1      num_src_ports    2.236229     0.442218  2.678447
14          tot_rate    1.219774     0.660888  1.880662
23         idle_mean    0.959776     0.877182  1.836958
11          tot_load    1.390806     0.431720  1.822526
9           src_load    1.405904     0.339776  1.745680
2      num_dst_ports    0.387380     1.340870  1.728250
12          src_rate    1.060573     0.572271  1.632844
25      src_ttl_mean    0.966497     0.659394  1.625890
26      dst_ttl_mean    1.251678     0.318018  1.569696
32   src_jitter_mean    0.916147     0.443279  1.359425
15          src_loss    0.867280     0.404891  1.272171
17              loss    0.997833     0.214661  1.212495
4           dst_pkts    0.835801     0.036001  0.871802
44            stos_0    0.717535     0.112912  0.830447
16          dst_loss    0.626682     0.118131  0.744812
31      run_time_sum    0.249031     0.443121  0.692151
34  src_int_pkt_mean    0.267705     0.358047  0.625752
0               mean    0.265592     0.341609  0.607201
7          dst_bytes    0.240278     0.125513  0.365791
28     dst_app_bytes    0.222900     0.141916  0.364816

In [17]:
class_names = ["Backdoor", "CommInj", "DoS", "Reconn", "normal"]
y_true = y_true.detach().cpu()
y_pred = y_pred.detach().cpu()

tp = y_true == y_pred
per_class_results = {}

# per attack feature importance
# focusing on correctly predicted classes
for c, name in enumerate(class_names):

    mask = tp & (y_true == c)

    if mask.sum().item() == 0:
        continue

    scores = total_importance[mask].mean(dim=0)

    per_attack = pd.DataFrame({
        "feature": feature_names,
        "importance": scores.numpy()
    })

    per_attack = per_attack.sort_values("importance",ascending=False)
    per_class_results[name] = per_attack

    print(f"\n{name}: {mask.sum().item()} samples")
    display(per_attack.head(10))

Backdoor: 38 samples

          feature  importance
26   dst_ttl_mean    2.544958
1   num_src_ports    2.462597
28  dst_app_bytes    1.885463
23      idle_mean    1.863839
7       dst_bytes    1.686881
25   src_ttl_mean    1.535246
17           loss    1.499800
16       dst_loss    1.376364
11       tot_load    1.159755
9        src_load    0.899507

CommInj: 49 samples

            feature  importance
15         src_loss    3.644860
11         tot_load    3.218323
9          src_load    3.084946
14         tot_rate    3.084208
12         src_rate    2.386732
17             loss    1.987459
23        idle_mean    1.586523
1     num_src_ports    1.129846
32  src_jitter_mean    1.036586
44           stos_0    0.926085

DoS: 91 samples

             feature  importance
14          tot_rate    3.495495
12          src_rate    3.198985
11          tot_load    2.863950
25      src_ttl_mean    2.435734
9           src_load    2.324835
32   src_jitter_mean    2.188235
1      num_src_ports    2.151218
31      run_time_sum    2.091739
0               mean    1.660816
34  src_int_pkt_mean    1.641770

Reconn: 29 samples

          feature  importance
2   num_dst_ports   16.028759
23      idle_mean    2.911275
9        src_load    1.595929
12       src_rate    1.487733
11       tot_load    1.478713
14       tot_rate    1.464350
26   dst_ttl_mean    1.368468
25   src_ttl_mean    0.855458
44         stos_0    0.838373
1   num_src_ports    0.644155

normal: 200 samples

            feature  importance
1     num_src_ports    3.641153
26     dst_ttl_mean    2.234034
23        idle_mean    1.833983
25     src_ttl_mean    1.574336
4          dst_pkts    1.509140
17             loss    1.497583
32  src_jitter_mean    1.353245
9          src_load    1.341872
15         src_loss    1.320565
11         tot_load    1.190470